on:
  - push
  - pull_request

name: build

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: actions/checkout@v3
      - name: Test and build the provider
        run: make
      - name: Check that checked-in generated files are current
        shell: bash
        run: if [[ `git status --porcelain` ]]; then echo "generated files have changed"; exit -1; fi;
